version: "3"
services: 
  postgresql:

    image: postgresql:15
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin1234
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin1234

    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin


